[package]
name = "arithmetic_progression"
version = "0.1.0"
authors = ["suzu-prg <suzu.prg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.8"
rayon = "0.8.2"